name: "Manual build (v4)"

on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: Godot version
        type: string
        required: true
        default: "4.2.1"

env:
  IMAGE_NAME: godot-headless

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo IMAGE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-v4
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ inputs.godot_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.godot_version }}
          build-args: GODOT_VERSION=${{ inputs.godot_version }}
